Simplify the renderRoutes method
FriendsOfECMAScript/ReactI18nRouting pull request #8
Opened 2018-06-26 18:11 UTC by benatespina

Because after v0.3.0 we have current locale decoupled from the `BrowseIntlProvider` itself, in order to improve the DX we can simplify the boilerplate around `renderRoutes` method hidden execution of the functions.

Before:
```javascript
// src/i18n/index.js

export default {
  formatIntlRoute: languageStrategy.formatIntlRoute,
  localeFromLocation: languageStrategy.localeFromLocation,
  messages: {en: messagesEn, es: messagesEs, eu: messagesEu, fr: messagesFr},
  renderRoutes: languageStrategy.renderRoutes(getLocale())(config),
};
```

After: 
```javascript
// src/i18n/index.js

export default {
  formatIntlRoute: languageStrategy.formatIntlRoute,
  localeFromLocation: languageStrategy.localeFromLocation,
  messages: {en: messagesEn, es: messagesEs, eu: messagesEu, fr: messagesFr},
  renderRoutes: languageStrategy.renderRoutes,
};
```

2018-06-26 21:20 UTC, gorkalaucirica approved these changes
Looks 👌 tests are failing though

2018-06-26 21:21 UTC, gorkalaucirica requested changes
Tests are failing

2018-12-13 09:49 UTC, benatespina commented
Ufff I have this PR abandoned, but I remember that I was not able to make tests work.
Could you guys have a look and merge this PR before #13??

2018-12-13 12:41 UTC, gorkalaucirica commented
@benatespina I've some doubts about `getLocale` usage. Its a singleton that gets difficult to manage in larger applications. We already had problems with that. 

I was thinking in something more declarative like this:

`languageStrategy.renderRoutes(locale, config)`

Even we could provide a React Component containing the context that could be something like this:

```jsx
import React from 'react';
import withI18nRouting from './withI18nRouting';

const Routes = ({config, i18nRouting}) => i18nRouting.renderRoutes(i18nRouting.locale, config);

export default withI18nRouting(Routes);
```

2018-12-13 13:25 UTC, benatespina commented
@gorkalaucirica  yeah, I understand your proposal and I totally agree with you but I think that you're mixing two different questions.

This PR only tries to simplify the `renderRoutes` function because I think that always can be the same boilerplate. If we try to port this PR to #13 we could hide this two functions inside library avoiding unnecessary boilerplate, at least from the moment, to improve DX.

```js
const renderRoutes = (locale, config) => languageStrategy.renderRoutes(locale)(config),
const LocaleContext = withI18nRouting(({i18nRouting, children}) => children(i18nRouting.locale));
```

2018-12-13 15:12 UTC, gorkalaucirica commented
@benatespina yes, I think we are talking about the same, but what differs your proposal from mine is 
that `getLocale()` is used. I think we should avoid that and look for this API:

`languageStrategy.renderRoutes(locale, config)`

The change in your code should be the following:

```diff
export default ({routes, locales, defaultLocale}) => ({
  localeFromLocation: localeFromLocation(locales, defaultLocale),
  formatIntlRoute: formatIntlRoute(routes, defaultLocale),
  renderRoutes: renderTranslatedRoutes(
    locales,
    routes,
    pathFromRouteForPathsAndLocale(defaultLocale, pathFromRoute),
-  )(getLocale())(routes),
+  )(locale, routes)
});
``` 

I was thinking about `LocaleContext` for the next release though. I prefer making 0.8.0 stable before adding new features.

2018-12-13 16:56 UTC, benatespina commented
Agree! We can stop this PR after #13 is merged and we can relaunch this DX improvement over the new codebase. 👌

2018-12-27 15:07 UTC, closed without merging